title: 
# email: wildmangrimesgip73.github.io
# description: >- # this means to ignore newlines until "baseurl:"
#   APP技术支持.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  douwantech

# Build settings
theme: minima
plugins:
  - jekyll-feed
